// ============================================================
// orOS Oracle — the prophecies (v1.0.0)
// Written for orOS. Every prophecy is true, and none of them helps.
// Data only: oracle.js picks from these lists.
//   P[lang][topic]  topics: time, love, work, yesno, general
//   K[topic]        keywords (accents stripped, lower case, either
//                   language): a word that starts with one of them
//                   sends the question to that topic
// The Greek and English lists are written separately; they are not
// translations of each other.
// ============================================================
(function (root) {
  "use strict";

  var P = {
    en: {
      time: [
        "By the end of the week, the week will have ended.",
        "Tomorrow will arrive exactly one day after today.",
        "It will happen at a moment. Possibly a Tuesday.",
        "Sooner than later, unless it is later than sooner.",
        "The clock already knows. It is just not saying.",
        "When it happens, it will be the present.",
        "Before then, there will be a little while.",
        "The day after it happens, it will have happened.",
        "Some of it will take time. The rest will take longer.",
        "At the right time, which is also the time it happens.",
        "Next year will come right after this one. Mark my words.",
        "It will be later than now. The oracle is certain of this.",
        "Before midnight, it will be evening.",
        "The answer arrives the moment you stop waiting, or slightly after.",
        "In the fullness of time, time will be full.",
        "One day you will look back on this day. It will be in the past.",
        "Spring follows winter. Sometimes it brings an umbrella.",
        "When the moon rises, it will be up.",
        "It will not happen yesterday.",
        "Somewhere between now and then, there is a Thursday.",
        "Within a lifetime. Probably yours.",
        "The hour approaches. All hours do.",
        "At some point you will check the time, and it will be a time.",
        "Soon is a place on the map. You are walking towards it.",
        "Hours from now, it will be hours from then.",
        "Not before the kettle boils, and not after the tea is cold.",
        "It is coming, at the usual speed of one second per second.",
        "By the time you read this again, you will have read it twice."
      ],
      love: [
        "Someone, somewhere, is thinking about lunch right now.",
        "Your heart will keep beating. That is a start.",
        "Love will find you, most likely in a place where you are.",
        "A person will smile today. Perhaps at you, perhaps at a dog.",
        "The one who loves you knows your name. Probably.",
        "There is someone who would share their umbrella with you, if it rained near them.",
        "You will be thought of by at least one person: you.",
        "A message will arrive. It may be from your bank.",
        "Somebody misses someone. The oracle cannot say who.",
        "Love is in the air, along with oxygen and a little dust.",
        "Your heart knows the answer. It is a muscle, though, and will not say.",
        "The stars say yes. The stars are very far away.",
        "Someone will hold the door for you and mean nothing by it, or something.",
        "You will meet someone tall, shorter than someone else.",
        "Affection is coming your way, at the speed of a slow cat.",
        "A pair of eyes will look at you. Possibly two pairs.",
        "Your next kiss will happen after your last one.",
        "The person you are thinking of is also thinking. About something.",
        "There is plenty of fish in the sea. Most of them are busy.",
        "Romance awaits where two paths cross, which is most corners.",
        "You will be loved for exactly who you are, by exactly who loves you.",
        "Something sweet is on its way. Check the cupboard.",
        "A heart will flutter. Hearts do that.",
        "Your soulmate exists, or will, or did.",
        "Someone admires your shoes. They have not said so.",
        "What is meant to be will be, and what is not, will be something else.",
        "Love will come when you least expect it, so expect it less.",
        "A warm hand will hold a cup of tea tonight. It may be yours."
      ],
      work: [
        "Money will change hands. Some of them may be yours.",
        "Your next payday will arrive on payday.",
        "A great opportunity is hiding behind a door. Doors are everywhere.",
        "You will receive an email. You will read it, or not.",
        "Hard work pays off, eventually, in some currency.",
        "The meeting will end. They always do.",
        "Your boss has a boss. Remember this in dark times.",
        "Riches await those who count them.",
        "A coin will cross your path. Pick it up only if it is yours.",
        "Your inbox will contain messages.",
        "Success is ahead of you, behind a few Mondays.",
        "You will be asked to do something. You will do it, or explain why not.",
        "A promotion is possible. Many things are.",
        "The report will be finished when it is done.",
        "Someone will say \"let's circle back\". You will circle.",
        "Your wallet holds exactly what is in it.",
        "Spend wisely and you will have spent.",
        "Fortune favours the bold. It also favours the early, the lucky and the rich.",
        "A deadline approaches. It is closer than it appears.",
        "There will be coffee at work. Not all of it good.",
        "Your career will go in a direction.",
        "An unexpected expense will be expected next time.",
        "You will be paid for some of what you do.",
        "Your effort will be noticed by at least one person: the oracle.",
        "Tomorrow you will work, or rest, or think about it.",
        "Every euro you save is a euro you still have.",
        "A spreadsheet somewhere has your name in it.",
        "Ambition will take you places. Bring snacks."
      ],
      yesno: [
        "Yes, in the cases where it is not no.",
        "The answer is the opposite of the other answer.",
        "No doubt about it, or very little.",
        "It is certain that something will happen.",
        "Absolutely, or close enough to it.",
        "The signs point in a direction.",
        "Ask again after you have asked.",
        "The oracle nods. Or it is the wind.",
        "Without question, this is a question.",
        "Yes and no are both words you know.",
        "The answer is clear to those who already know it.",
        "Most likely, with a small chance of otherwise.",
        "If it is so, then so it is.",
        "One of the two will turn out to be true.",
        "There is a fifty percent chance of one of two outcomes.",
        "The answer lies within. Within the answer.",
        "It is as it seems, unless it seems otherwise.",
        "Do not count on it, and do not count it out.",
        "The coin has two sides. Both are correct.",
        "Indeed, as far as indeed goes.",
        "Yes. The oracle reserves the right to have meant no.",
        "It depends, and on what it depends, it depends.",
        "Things will turn out one way or another.",
        "The oracle says what you hope, in a voice you cannot hear.",
        "Certainly, eventually, in a way.",
        "Neither yes nor no would be lying to you.",
        "If you have to ask, you have asked.",
        "It will be so, wherever it is so."
      ],
      general: [
        "Something will happen, and then something else.",
        "The answer is closer than it looks. It is in this sentence.",
        "Today you will breathe many times. Count none of them.",
        "You will see the colour blue before the day is over.",
        "A door will open. Then, most likely, it will close.",
        "Water will be wet tomorrow as well.",
        "Your shadow will follow you wherever there is light.",
        "You will eat something. It will be food.",
        "A great change is coming. The seasons, for instance.",
        "Look up. The ceiling is still there.",
        "You are reading this right now. The oracle saw it coming.",
        "The road ahead has a next step. Then another.",
        "What goes up will be up for a while.",
        "A bird will sing somewhere today. You may not hear it.",
        "Your keys are where you left them.",
        "A small thing will matter to someone.",
        "You will forget something unimportant. Then remember it at night.",
        "The future holds many things, mostly the future.",
        "Somewhere a kettle is boiling. That is a good sign.",
        "The stars are aligned in their usual places.",
        "Every journey begins with a step, and so does every walk to the fridge.",
        "Be careful what you wish for. Also what you microwave.",
        "Your phone will ask you for something. Say yes, or later.",
        "There is wisdom in this answer. Look for it carefully.",
        "The oracle has spoken. That is the main thing.",
        "Things will be as they are, then as they become.",
        "A sock is missing. It is not lost, merely elsewhere.",
        "You will remember this prophecy, or a different one.",
        "In the end, everything ends. Even this sentence."
      ]
    },
    el: {
      time: [
        "Μέχρι το τέλος της εβδομάδας, η εβδομάδα θα έχει τελειώσει.",
        "Αύριο θα είναι σήμερα για όσους ζουν αύριο.",
        "Θα γίνει κάποια στιγμή. Πιθανώς Τρίτη.",
        "Νωρίτερα απ' ό,τι αργότερα, εκτός αν είναι αργότερα.",
        "Το ρολόι ξέρει ήδη. Απλώς δεν το λέει.",
        "Όταν συμβεί, θα είναι το παρόν.",
        "Μέχρι τότε θα περάσει λίγος καιρός. Ή λίγο παραπάνω.",
        "Την επόμενη μέρα, θα έχει ήδη συμβεί.",
        "Στην ώρα του, που είναι και η ώρα που θα γίνει.",
        "Του χρόνου θα έρθει αμέσως μετά από φέτος.",
        "Θα είναι αργότερα από τώρα. Αυτό το Μαντείο το ξέρει σίγουρα.",
        "Πριν από τα μεσάνυχτα θα έχει βραδιάσει.",
        "Η απάντηση έρχεται τη στιγμή που θα πάψεις να περιμένεις, ή λίγο μετά.",
        "Μια μέρα θα θυμηθείς τη σημερινή. Θα είναι στο παρελθόν.",
        "Μετά τον χειμώνα έρχεται η άνοιξη. Καμιά φορά με ομπρέλα.",
        "Όταν ανατείλει το φεγγάρι, θα είναι ψηλά.",
        "Χθες σίγουρα όχι.",
        "Κάπου ανάμεσα στο τώρα και στο τότε υπάρχει μια Πέμπτη.",
        "Μέσα σε μια ζωή. Μάλλον τη δική σου.",
        "Η ώρα πλησιάζει. Όλες οι ώρες πλησιάζουν.",
        "Κάποια στιγμή θα κοιτάξεις το ρολόι, και θα δείχνει ώρα.",
        "Το «σύντομα» είναι ένα μέρος στον χάρτη. Περπατάς προς τα εκεί.",
        "Όχι πριν βράσει το νερό, και όχι αφού κρυώσει το τσάι.",
        "Έρχεται, με τη συνηθισμένη ταχύτητα: ένα δευτερόλεπτο το δευτερόλεπτο.",
        "Με τον καιρό, ο καιρός θα αλλάξει.",
        "Ό,τι είναι να γίνει τον Αύγουστο, θα γίνει καλοκαίρι.",
        "Μόλις το διαβάσεις ξανά, θα το έχεις διαβάσει δύο φορές.",
        "Υπομονή. Η υπομονή κρατάει όσο χρειάζεται."
      ],
      love: [
        "Κάποιος, κάπου, σκέφτεται αυτή τη στιγμή το μεσημεριανό του.",
        "Η καρδιά σου θα συνεχίσει να χτυπά. Καλή αρχή.",
        "Η αγάπη θα σε βρει, πιθανότατα εκεί που βρίσκεσαι.",
        "Κάποιος θα χαμογελάσει σήμερα. Ίσως σε σένα, ίσως σε έναν σκύλο.",
        "Όποιος σε αγαπά ξέρει το όνομά σου. Μάλλον.",
        "Τουλάχιστον ένας άνθρωπος θα σε σκεφτεί σήμερα: εσύ.",
        "Θα έρθει ένα μήνυμα. Μπορεί να είναι από την τράπεζα.",
        "Κάποιος λείπει σε κάποιον. Το Μαντείο δεν λέει ποιος.",
        "Η αγάπη είναι στον αέρα, μαζί με το οξυγόνο και λίγη σκόνη.",
        "Η καρδιά σου ξέρει την απάντηση. Είναι όμως μυς και δεν μιλάει.",
        "Τα άστρα λένε ναι. Τα άστρα είναι πολύ μακριά.",
        "Θα γνωρίσεις κάποιον ψηλό, πιο κοντό από κάποιον άλλον.",
        "Τρυφερότητα έρχεται προς τα σένα, με την ταχύτητα μιας νωθρής γάτας.",
        "Δυο μάτια θα σε κοιτάξουν. Ίσως και τέσσερα.",
        "Το επόμενο φιλί σου θα γίνει μετά το προηγούμενο.",
        "Ο άνθρωπος που σκέφτεσαι σκέφτεται κι αυτός. Κάτι.",
        "Η θάλασσα έχει πολλά ψάρια. Τα περισσότερα είναι απασχολημένα.",
        "Θα σε αγαπήσουν ακριβώς γι' αυτό που είσαι, ακριβώς όσοι σε αγαπούν.",
        "Κάτι γλυκό έρχεται. Κοίτα στο ντουλάπι.",
        "Μια καρδιά θα φτερουγίσει. Οι καρδιές το κάνουν αυτό.",
        "Η αδελφή ψυχή σου υπάρχει, ή θα υπάρξει, ή υπήρξε.",
        "Κάποιος θαυμάζει τα παπούτσια σου. Δεν σου το έχει πει.",
        "Ό,τι είναι γραφτό θα γίνει. Ό,τι δεν είναι, θα γίνει κάτι άλλο.",
        "Η αγάπη έρχεται όταν δεν την περιμένεις. Περίμενέ την λιγότερο.",
        "Απόψε ένα ζεστό χέρι θα κρατήσει ένα φλιτζάνι τσάι. Ίσως το δικό σου.",
        "Κάποιος θα σου κρατήσει την πόρτα. Ίσως να μη σημαίνει τίποτα, ίσως κάτι.",
        "Θα σου πουν «καλημέρα» και θα το εννοούν, πάνω κάτω.",
        "Όπου δύο δρόμοι διασταυρώνονται, περιμένει ο έρωτας. Δηλαδή σε κάθε γωνία."
      ],
      work: [
        "Χρήματα θα αλλάξουν χέρια. Κάποια από τα χέρια μπορεί να είναι δικά σου.",
        "Ο επόμενος μισθός σου θα έρθει τη μέρα της πληρωμής.",
        "Μια μεγάλη ευκαιρία κρύβεται πίσω από μια πόρτα. Πόρτες υπάρχουν παντού.",
        "Θα λάβεις ένα email. Θα το διαβάσεις, ή όχι.",
        "Η σκληρή δουλειά αποδίδει κάποτε, σε κάποιο νόμισμα.",
        "Η σύσκεψη θα τελειώσει. Πάντα τελειώνουν.",
        "Κι ο προϊστάμενός σου έχει προϊστάμενο. Θυμήσου το στις δύσκολες ώρες.",
        "Τα πλούτη περιμένουν όσους τα μετρούν.",
        "Ένα κέρμα θα βρεθεί στον δρόμο σου. Σήκωσέ το μόνο αν είναι δικό σου.",
        "Τα εισερχόμενά σου θα έχουν μηνύματα.",
        "Η επιτυχία είναι μπροστά σου, πίσω από μερικές Δευτέρες.",
        "Θα σου ζητήσουν κάτι. Θα το κάνεις, ή θα εξηγήσεις γιατί όχι.",
        "Μια προαγωγή είναι πιθανή. Πολλά πράγματα είναι.",
        "Η αναφορά θα τελειώσει όταν τελειώσει.",
        "Κάποιος θα πει «το ξαναβλέπουμε». Θα το ξαναδείτε.",
        "Το πορτοφόλι σου έχει ακριβώς όσα έχει μέσα.",
        "Ξόδεψε με σύνεση, και θα έχεις ξοδέψει.",
        "Η τύχη ευνοεί τους τολμηρούς. Ευνοεί και τους πρωινούς, τους τυχερούς και τους πλούσιους.",
        "Μια προθεσμία πλησιάζει. Είναι πιο κοντά απ' όσο φαίνεται.",
        "Στη δουλειά θα έχει καφέ. Όχι πάντα καλό.",
        "Η καριέρα σου θα πάει προς κάποια κατεύθυνση.",
        "Ένα απρόοπτο έξοδο, την επόμενη φορά, θα είναι προβλέψιμο.",
        "Θα πληρωθείς για κάποια από όσα κάνεις.",
        "Την προσπάθειά σου τη βλέπει τουλάχιστον ένας: το Μαντείο.",
        "Αύριο θα δουλέψεις, ή θα ξεκουραστείς, ή θα το σκεφτείς.",
        "Κάθε ευρώ που αποταμιεύεις είναι ένα ευρώ που έχεις ακόμα.",
        "Κάπου υπάρχει ένα λογιστικό φύλλο με το όνομά σου.",
        "Η φιλοδοξία θα σε πάει μακριά. Πάρε και κολατσιό."
      ],
      yesno: [
        "Ναι, στις περιπτώσεις που δεν είναι όχι.",
        "Η απάντηση είναι το αντίθετο της άλλης απάντησης.",
        "Χωρίς καμία αμφιβολία, ή με πολύ λίγη.",
        "Είναι βέβαιο ότι κάτι θα συμβεί.",
        "Απολύτως, ή κάτι πολύ κοντά σε αυτό.",
        "Τα σημάδια δείχνουν προς μια κατεύθυνση.",
        "Ρώτα ξανά, αφού ρωτήσεις.",
        "Το Μαντείο γνέφει. Ή είναι ο αέρας.",
        "Αναμφίβολα, πρόκειται για ερώτηση.",
        "Το «ναι» και το «όχι» είναι και τα δύο λέξεις που ξέρεις.",
        "Η απάντηση είναι ξεκάθαρη σε όσους την ξέρουν ήδη.",
        "Πιθανότατα, με μια μικρή πιθανότητα για το αντίθετο.",
        "Αν είναι έτσι, τότε έτσι είναι.",
        "Ένα από τα δύο θα αποδειχθεί αληθινό.",
        "Υπάρχει πενήντα τοις εκατό πιθανότητα για ένα από δύο ενδεχόμενα.",
        "Η απάντηση βρίσκεται μέσα. Μέσα στην απάντηση.",
        "Είναι όπως φαίνεται, εκτός αν φαίνεται αλλιώς.",
        "Μην το υπολογίζεις, αλλά και μην το αποκλείεις.",
        "Το κέρμα έχει δύο όψεις. Και οι δύο είναι σωστές.",
        "Ναι. Το Μαντείο διατηρεί το δικαίωμα να εννοούσε όχι.",
        "Εξαρτάται. Κι από αυτό που εξαρτάται, εξαρτάται.",
        "Τα πράγματα θα πάνε με τον έναν ή με τον άλλον τρόπο.",
        "Σίγουρα, κάποτε, κατά κάποιον τρόπο.",
        "Ούτε το «ναι» ούτε το «όχι» θα σου έλεγε ψέματα.",
        "Αφού χρειάστηκε να ρωτήσεις, ρώτησες.",
        "Θα γίνει έτσι, όπου γίνεται έτσι.",
        "Μάλλον ναι, ή μάλλον όχι. Μάλλον.",
        "Ο χρησμός είναι διπλός, όπως στους Δελφούς. Διάλεξε."
      ],
      general: [
        "Κάτι θα συμβεί, και μετά κάτι άλλο.",
        "Η απάντηση είναι πιο κοντά απ' όσο νομίζεις. Είναι σε αυτή την πρόταση.",
        "Σήμερα θα αναπνεύσεις πολλές φορές. Μην τις μετρήσεις.",
        "Πριν τελειώσει η μέρα θα δεις κάτι μπλε.",
        "Μια πόρτα θα ανοίξει. Μετά, κατά πάσα πιθανότητα, θα κλείσει.",
        "Και αύριο το νερό θα είναι βρεγμένο.",
        "Η σκιά σου θα σε ακολουθεί όπου υπάρχει φως.",
        "Θα φας κάτι. Θα είναι φαγητό.",
        "Μια μεγάλη αλλαγή έρχεται. Οι εποχές, για παράδειγμα.",
        "Κοίτα ψηλά. Το ταβάνι είναι ακόμα εκεί.",
        "Αυτή τη στιγμή διαβάζεις αυτό. Το Μαντείο το είχε προβλέψει.",
        "Ο δρόμος μπροστά σου έχει ένα επόμενο βήμα. Και μετά άλλο ένα.",
        "Ό,τι ανεβαίνει, θα μείνει πάνω για λίγο.",
        "Κάπου σήμερα θα κελαηδήσει ένα πουλί. Ίσως να μην το ακούσεις.",
        "Τα κλειδιά σου είναι εκεί που τα άφησες.",
        "Κάτι μικρό θα έχει σημασία για κάποιον.",
        "Θα ξεχάσεις κάτι ασήμαντο. Θα το θυμηθείς το βράδυ.",
        "Το μέλλον κρύβει πολλά, κυρίως το μέλλον.",
        "Κάπου βράζει ένα μπρίκι. Καλό σημάδι.",
        "Τα άστρα είναι στις συνηθισμένες τους θέσεις.",
        "Κάθε ταξίδι ξεκινά με ένα βήμα. Και κάθε διαδρομή ως το ψυγείο.",
        "Πρόσεχε τι εύχεσαι. Και τι βάζεις στον φούρνο μικροκυμάτων.",
        "Το κινητό σου θα σου ζητήσει κάτι. Πες ναι, ή αργότερα.",
        "Σε αυτή την απάντηση κρύβεται σοφία. Ψάξε την προσεκτικά.",
        "Το Μαντείο μίλησε. Αυτό είναι το σημαντικό.",
        "Τα πράγματα θα είναι όπως είναι, και μετά όπως θα γίνουν.",
        "Μια κάλτσα λείπει. Δεν χάθηκε, απλώς είναι αλλού.",
        "Θα θυμάσαι αυτόν τον χρησμό, ή κάποιον άλλον.",
        "Στο τέλος όλα τελειώνουν. Ακόμα και αυτή η πρόταση."
      ]
    }
  };

  // Keyword starts, accents stripped. Checked in this order:
  // time, love, work, yesno; anything else is general.
  var K = {
    time: ["when", "tomorrow", "today", "tonight", "soon", "year", "month", "week", "how long", "how soon",
           "ποτε", "αυριο", "σημερα", "αποψε", "συντομα", "χρονια", "του χρονου", "φετος", "μηνα", "εβδομαδα", "ποσο καιρο", "ποσο θα"],
    love: ["love", "loves", "crush", "date me", "kiss", "marry", "marriage", "boyfriend", "girlfriend", "partner",
           "husband", "wife", "heart", "romance", "soulmate", "relationship", "ex ",
           "αγαπ", "ερωτ", "φιλι", "παντρ", "γαμο", "αγορι", "κοπελ", "συντροφ", "συζυγ", "αντρα", "γυναικα",
           "καρδια", "σχεση", "πρωην", "ραντεβου", "μου αρεσει"],
    work: ["work", "job", "boss", "money", "pay", "salary", "rich", "career", "promotion", "raise", "business",
           "office", "interview", "exam", "lottery", "cash", "euro", "debt", "invest",
           "δουλει", "εργασ", "αφεντικ", "προισταμεν", "λεφτ", "χρημ", "μισθ", "πλουσ", "καριερ", "προαγωγ",
           "αυξηση", "επιχειρ", "γραφει", "συνεντευξ", "εξετασ", "λοττο", "τζοκερ", "ευρω", "χρεο", "δανει"],
    // a yes/no question starts with one of these
    yesno: ["will ", "is ", "are ", "am ", "should ", "can ", "could ", "do ", "does ", "did ", "would ", "shall ",
            "θα ", "ειναι ", "πρεπει ", "μπορω ", "μπορει ", "αξιζει ", "να ", "υπαρχει ", "εχω ", "εχει "]
  };

  var api = { P: P, K: K };
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.ORACLE_WORDS = api;
})(typeof window !== "undefined" ? window : this);
